// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhrskytltnhmzswdxqxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVocnNreXRsdG5obXpzd2R4cXhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MDQ3MzcsImV4cCI6MjA2Njk4MDczN30.JpglxZ1zFyXBA1lFl68FQ1EfSkR28-mZ9Rmyr3z8-OQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});